pipeline:
  install:
    image: node:20-slim
    commands:
      - npm ci
      - npm run build
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
when:
  event: tag
  tag: v*