pipeline:
  install:
    image: node:20-slim
    commands:
      - npm ci
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      folder: template-uuid-instantiator
when:
  event: tag
  tag: v*