pipeline:
  install:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm ci
  prettier-check:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npx prettier --check .
  lint:
    image: danlynn/ember-cli:4.4.0
    group: lint
    commands:
      - npm run lint
  test:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm run test || exit 0
when:
  event: pull_request